# SHADERS
Alt+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_DarkLines_HQ.glsl;~~/shaders/Anime4K_ThinLines_HQ.glsl"; show-text "Anime4k: Lines" #menu: Shaders > Anime4K
Alt+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Upscale_Original_x2"; show-text "Anime4k: Upscale Original" #menu: Shaders > Anime4K
Alt+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Upscale_CNN_x2_UL.glsl;~~/shaders/Anime4K_ThinLines_HQ.glsl"; show-text "Anime4k: Upscale x2" #menu: Shaders > Anime4K

# mpv360
# --- 360 PROJECTION SWITCHES (Direct Filter Control) ---
# Tap k to cycle through formats and display the current mode
k cycle-values vf "v360=input=eac:output=equirect:w=1920:h=1080:interp=linear" "v360=input=equirect:output=equirect:w=1920:h=1080:interp=linear" "v360=input=dfisheye:output=equirect:w=1920:h=1080:interp=linear" "v360=input=hequirect:output=equirect:w=1920:h=1080:interp=linear" "v360=input=cylindrical:output=equirect:w=1920:h=1080:interp=linear" ; set osc yes ; show-text "360 Mode: ${vf}"

# PAN & SCAN
 Ctrl++     add video-zoom  0.1          #menu: Pan & Scan > Increase Size
 Ctrl+-     add video-zoom -0.1          #menu: Pan & Scan > Decrease Size
 _          ignore                       #menu: Pan & Scan > -
 Ctrl+Right  add video-pan-x -0.01        #menu: Pan & Scan > Move Left
 Ctrl+Left add video-pan-x  0.01        #menu: Pan & Scan > Move Right
 _          ignore                       #menu: Pan & Scan > -
 Ctrl+Down    add video-pan-y -0.01        #menu: Pan & Scan > Move Up
 Ctrl+Up  add video-pan-y  0.01        #menu: Pan & Scan > Move Down
 _          ignore                       #menu: Pan & Scan > -
 w          add panscan -0.1             #menu: Pan & Scan > Decrease Height
 W          add panscan  0.1             #menu: Pan & Scan > Increase Height
 _          ignore                       #menu: Pan & Scan > -
 o    set video-zoom 0; set video-pan-x 0; set video-pan-y 0 #menu: Pan & Scan > Reset

# NAVIGATION
 p          show-text ${playlist} 5000           #menu: Navigate > Playlist
 P          playlist-prev                #menu: Navigate > Previous File
 N          playlist-next                #menu: Navigate > Next File
 _          ignore                       #menu: Navigate > -
 Home       script-message mpv.net playlist-first #menu: Navigate > First File
 End        script-message mpv.net playlist-last #menu: Navigate > Last File
 _          ignore                       #menu: Navigate > -
 Ctrl+S       add chapter  1               #menu: Navigate > Next Chapter
 PGDWN      add chapter -1               #menu: Navigate > Previous Chapter
 _          ignore                       #menu: Navigate > -
 .          frame-step                   #menu: Navigate > Jump Next Frame
 ,          frame-back-step              #menu: Navigate > Jump Previous Frame
 _          ignore                       #menu: Navigate > -
 Right      seek  5                      #menu: Navigate > Jump 7 sec forward
 Left       seek -5                      #menu: Navigate > Jump 7 sec backward
 _          ignore                       #menu: Navigate > -
  _           ignore                 #menu: Navigate > Titles
 _           ignore                 #menu: Navigate > Chapters

 >          playlist-next
 <          playlist-prev

#======
#VOLUME
#======
0 add volume +5
9 add volume -5

# Percise volume control
) add volume +1
( add volume -1

WHEEL_UP add volume  1
WHEEL_DOWN add volume -1

