sub-visibility=yes

alang: jpn, jp, en
slang: jpn, jp, en
audio-file-auto=fuzzy
autoload-files=yes
autoload-files=yes
save-position-on-quit=yes
autofit-larger=100%x100%
#geometry="calc(30% - 50%):30%"
autofit=80%x80%
image-display-duration=inf
osc=no
H cycle-values keep-open "yes" "no"
mpv --osd-fractions --osd-level=2


########
# Subs #
########

blend-subtitles=no
sub-ass-vsfilter-blur-compat=yes		# Backward compatibility for vsfilter fansubs
sub-ass-scale-with-window=no			# May have undesired effects with signs being misplaced.
sub-auto=fuzzy                         		# external subs don't have to match the file name exactly to autoload
# sub-gauss=0.6					# Some settings fixing VOB/PGS subtitles (creating blur & changing yellow subs to gray)
sub-file-paths-append=ass               	# search for external subs in these relative subdirectories
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes       		# try to correctly show embedded subs when seeking
embeddedfonts=yes				# use embedded fonts for SSA/ASS subs
sub-fix-timing=no                       	# do not try to fix gaps (which might make it worse in some cases). Enable if there are scenebleeds.

# Subs - Forced # 

sub-font=Open Sans SemiBold
sub-font-size=46
sub-blur=0.3
sub-border-color=0.0/0.0/0.0/0.8
sub-border-size=3.2
sub-color=0.9/0.9/0.9/1.0
sub-margin-x=100
sub-margin-y=50
sub-shadow-color=0.0/0.0/0.0/0.25
sub-shadow-offset=0

# SCREENSHOTS
screenshot-directory = 'C:\Users\Rafay\Desktop\screenshots'
screenshot-high-bit-depth=yes
screenshot-tag-colorspace=yes
screenshot-format=jpeg
screenshot-png-compression=1
screenshot-template = 'mpvscreenshot-%tY-%tm-%td-%tHh%tMm%tSs%wT'

# VIDEO
vd-lavc-threads = 0
vd-queue-enable = yes
vd-queue-max-bytes = 2GiB
vd-queue-max-samples = 60
vd-queue-max-secs = 2

#profile=high-quality
#vo=gpu-next
#scale-antiring=0.6

# ON SCREEN DISPLAY
osd-bar = no
osd-font = "Gordita Medium"
osd-font-size = 36
osd-bold = no
osd-color = "#ffffff"
osd-border-size = 2.0
osd-border-color = "#262626"


[youtube-360]
profile-cond=string.match(filename, "360") ~= nil or string.match(get("media-title", ""), "360") ~= nil or string.match(get("path", ""), "360") ~= nil
# Tell the script to use EAC input for these files
script-opts-add=mpv360-input=eac
# To Fix lag when looking around
vf=v360=input=eac:output=equirect:w=1920:h=1080:interp=linear
# Force the OSC to be enabled and set to 'auto' visibility
osc=yes
script-opts-add=osc-visibility=auto
# This ensures the OSC isn't hidden by the script on start
script-opts-add=mpv360-auto_hide_osc=no
keep-open = no